### PR TITLE
fix: destructuring of undefined or null variables. fixes #46

### LINKED ISSUE #46: clientside error when hmr is false: Cannot destructure property `apply` of 'undefined' or 'null'.
When `hmr` option is `false`, an error occurs clientside.

- Webpack Version: `v4.26.1`
- Operating System (or Browser): `Windows 10, Chrome 71.0.3578.80`
- Node Version: `v10.14.1`
- webpack-plugin-dev Version: `v0.1.2`

### How Do We Reproduce?

https://github.com/G-Rath/js-bugs/tree/webpack-plugin-serve/hmr-false-bug

### Expected Behavior
No errors in console.

### Actual Behavior

Errors in console:
```
client-hmr.js:13 Uncaught TypeError: Cannot destructure property `apply` of 'undefined' or 'null'.
    at Object.eval (webpack:///(:55555/webpack)-plugin-serve/lib/client-hmr.js?:13:41)
    at eval (webpack:///(:55555/webpack)-plugin-serve/lib/client-hmr.js?:61:30)
    at Object../node_modules/webpack-plugin-serve/lib/client-hmr.js (output.js:129)
    at __webpack_require__ (output.js:20)
    at eval (webpack:///(:55555/webpack)-plugin-serve/lib/client.js?:11:21)
    at Object../node_modules/webpack-plugin-serve/lib/client.js (output.js:151)
    at __webpack_require__ (output.js:20)
    at eval (webpack:///(:55555/webpack)-plugin-serve/client.js?:24:3)
    at eval (webpack:///(:55555/webpack)-plugin-serve/client.js?:25:3)
    at Object../node_modules/webpack-plugin-serve/client.js (output.js:118)
```

### PR DESCRIPTION
**Pull request by PlayMa256**
This PR contains:

- [X] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [X] no

If yes, please describe the breakage.

### Please Describe Your Changes
When destructuring `module.hot`, when `hmr:false`, `module.hot` does not exist, so it would throw an error. 

Fix #46

### CODE REVIEW

File: lib/client/hmr.js [hunk 1]
```diff
@@ -10,7 +10,7 @@
 */
 const { error, info, refresh, warn } = require('./log');
 
-const { apply, check, status } = module.hot;
+const { apply, check, status } = module.hot || {};
```
Comment (shellscape) [inline lib/client/hmr.js]: since these methods are only used in the `replace` method, we should move this assignment into that function.
