### PR TITLE
fix: z-index on overlays set to max allowed. fix #81

### LINKED ISSUE #81: Ensure wps-status indicators are always top z-index on page
### Feature Use Case
Current problem: Using WPS on a legacy codebase where I'm switching the build over from gulp. Legacy codebase has styles I cannot safely alter without triggering full-scale regression testing. If the z-index is too high on an element (the top-nav in my case), the wps-status indicator is hidden from view.

See attached animated gif.
wps-progress-indicator

### Feature Proposal
One of two options come to mind:

Setting the z-index of the WPS progress widget(s) to the max allowed z-index of 2147483647 ([StackOverflow answer on max z-index](https://stackoverflow.com/questions/491052/minimum-and-maximum-value-of-z-index))

**OR**

Dynamically find highest z-index on the page post-render and add 1 to that number for the progress widget(s). ([Find highest z-index](https://www.willmaster.com/blog/javascript/z-index-range.php))

### PR DESCRIPTION
**Pull request by PlayMa256**
This PR contains:

- [x] bugfix
- [X] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [X] no

As #81 suggested and we also had discussed before on the approach we should use to set those overlays on top of every possible scenario, be aware that, i preferred to decrease -2 on the max `z-index` allowed as a cautions action, to not walk on the edge every time, so we have a margin of error.

### CODE REVIEW

File: lib/client/overlays/progress.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ const css = `
 }
 
 #${ns}-percent-value {
-  alignment-baseline: middle;
+  dominant-baseline: middle;
```
Comment (PlayMa256) [inline lib/client/overlays/progress.js]: also fixed alignment on the status overlay, it was giving me OCD :rofl:

Comment (shellscape) [reply lib/client/overlays/progress.js]: What's the explanation for this change?
