### PR TITLE
fix: use static hmr filenames

### LINKED ISSUE #60: cheap-module-source-map bug
- Webpack Version: 4.27.1
- Operating System (or Browser): macOS Mojave 
- Node Version: 10.13
- webpack-plugin-serve Version: 0.2.2

### How Do We Reproduce?

1. Use react example in recipes folder of this repo
2. Change webpack config `devtool` to `cheap-module-source-map` value
3. Run server and change some code for hot reload

### Expected Behavior
server should work

### Actual Behavior
server stops on error

```
/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/SourceMapDevToolPlugin.js:36
        if (asset.sourceAndMap) {
                  ^

TypeError: Cannot read property 'sourceAndMap' of undefined
    at getTaskForFile (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/SourceMapDevToolPlugin.js:36:12)
    at files.forEach (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/SourceMapDevToolPlugin.js:136:20)
    at Array.forEach (<anonymous>)
    at compilation.hooks.afterOptimizeChunkAssets.tap (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/SourceMapDevToolPlugin.js:130:12)
    at SyncHook.eval [as call] (eval at create (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:14:1)
    at SyncHook.lazyCompileHook (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/Compilation.js:1313:42)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:10:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/Users/a/repos/github/webpack-plugin-serve/recipes/react/node_modules/webpack/lib/Compilation.js:1309:36)
error Command failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by shellscape**
This PR contains:

- [x] bugfix
- [ ] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [x] metadata

### Breaking Changes?

- [x] yes
- [ ] no

This PR introduces a breaking change, though it's not likely to impact our modest user base at this time: if a user has introduced a `HotModuleReplacementPlugin` instance to the configuration's `plugins` before the `WebpackPluginServe` instance, this plugin with throw an exception.

Previously, we were trying to be cute and work around that by modifying webpack internals. That was a noble goal initially, but with the introduction of MultiCompiler support, the complexity of the code required to do so increased significantly, and to make that work with #60 will add even more. All of that points to increased fragility of our code to work around things in webpack. Keeping that complexity will ultimately make upgrades harder for us moving forward.

Throwing an error requesting the user remove the plugin is ultimately a simpler solution for all parties.

### Please Describe Your Changes

Fixes #60.

So! When implementing MultiCompiler support, it appears I jumped the shark a bit. One component of MultiCompiler support was that we started tagging each compiler with a UUID of our own. That was a late addition to the overall solution, and came after hooking `additionalChunkAssets`, `chunkHash`, and a few others - with the goal of overriding the HMR filename options.

### CODE REVIEW

**Comment by shellscape** [comment]
@pronevich @TrySound please review as well

File: lib/hmr-plugin.js [hunk 1]
```diff
@@ -8,130 +8,35 @@
...
   );
   if (!hasHMRPlugin) {
     addPlugin(compiler);
   } else {
-    log.warn(
+    log.error(
       'webpack-plugin-serve adds HotModuleReplacementPlugin automatically. Please remove it from your config.'
     );
+    throw new PluginExistsError(
+      'HotModuleReplacementPlugin exists in the specified configuration.'
```
Comment (sibelius) [inline lib/hmr-plugin.js]: maybe provide a guide to solve this

like checking a FAQ, or saying that user should remove HotModuleReplacementPlugin from their webpack config

**Comment by shellscape** [comment]
OK. Going to merge this, but am going to hold off on publishing until we get some more tests in place. I will try and get that done at some point tomorrow. If anyone else would like to submit additional tests, it would be welcome.
